# Generated by Django 6.0.3 on 2026-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='has_drop_shadow',
            field=models.BooleanField(default=False, verbose_name='photo drop shadow'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='has_photo_accents',
            field=models.BooleanField(default=False, verbose_name='photo accents'),
        ),
    ]
