# Generated by Django 5.2.6 on 2025-09-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0002_casestudyprofile_feature_promocard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseStudyProfile',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='PromoCard',
        ),
    ]
