# Generated by Django 5.2.6 on 2026-03-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0005_counter'),
        ('djangocms_frontend', '0002_migrate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsCard',
            fields=[
            ],
            options={
                'verbose_name': 'Benefits Card',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='BenefitsPanel',
            fields=[
            ],
            options={
                'verbose_name': 'Benefits Panel',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
            ],
            options={
                'verbose_name': 'Carousel Item',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Container1ColText',
            fields=[
            ],
            options={
                'verbose_name': 'Single column text container',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='ContainerWithGrid',
            fields=[
            ],
            options={
                'verbose_name': 'Grid section',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='ContentTeaser',
            fields=[
            ],
            options={
                'verbose_name': 'Content Teaser',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='CTAPanel',
            fields=[
            ],
            options={
                'verbose_name': 'CTA Panel',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
            ],
            options={
                'verbose_name': 'Feature Item',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
            ],
            options={
                'verbose_name': 'Features',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
            ],
            options={
                'verbose_name': 'Footer',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
            ],
            options={
                'verbose_name': 'Hero',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='HorizontalPlanCard',
            fields=[
            ],
            options={
                'verbose_name': 'Horizontal Plan Card',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='LinksListContainer',
            fields=[
            ],
            options={
                'verbose_name': 'Links List Container',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='LogoCarousel',
            fields=[
            ],
            options={
                'verbose_name': 'Carousel',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='MembershipPlans',
            fields=[
            ],
            options={
                'verbose_name': 'Membership Plans',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
            ],
            options={
                'verbose_name': 'Navbar',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='PeopleCard',
            fields=[
            ],
            options={
                'verbose_name': 'People Card',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='PlanCard',
            fields=[
            ],
            options={
                'verbose_name': 'Plan Card',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='QuotePanelContainer',
            fields=[
            ],
            options={
                'verbose_name': 'Quote Panel',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='QuotePanelItem',
            fields=[
            ],
            options={
                'verbose_name': 'Quote Panel Item',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='RelatedPeople',
            fields=[
            ],
            options={
                'verbose_name': 'Related People',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='TeaserContent',
            fields=[
            ],
            options={
                'verbose_name': 'Teaser Content',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='TeaserMedia',
            fields=[
            ],
            options={
                'verbose_name': 'Teaser Media',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='TimelineContainer',
            fields=[
            ],
            options={
                'verbose_name': 'Timeline',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.DeleteModel(
            name='HeroPlugin',
        ),
    ]
