# Generated by Django 5.2.6 on 2026-03-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0006_benefitscard_benefitspanel_carouselitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureHanging',
        ),
        migrations.AlterModelOptions(
            name='container1coltext',
            options={'managed': False, 'verbose_name': 'Single Column'},
        ),
        migrations.AlterModelOptions(
            name='containerwithgrid',
            options={'managed': False, 'verbose_name': 'Grid Section'},
        ),
    ]
