# Generated by Django 6.0.3 on 2026-03-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0006_benefitscard_benefitspanel_carouselitem_and_more'),
        ('djangocms_frontend', '0002_migrate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCard',
            fields=[
            ],
            options={
                'verbose_name': 'Client Card',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='CodeBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Code Block',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='CounterContainer',
            fields=[
            ],
            options={
                'verbose_name': 'Counter Panel',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
            ],
            options={
                'verbose_name': 'Heading',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='MilestoneCard',
            fields=[
            ],
            options={
                'verbose_name': 'Milestone Card',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='ResponsiveTable',
            fields=[
            ],
            options={
                'verbose_name': 'Responsive Table',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Spacing',
            fields=[
            ],
            options={
                'verbose_name': 'Spacing',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.AlterModelOptions(
            name='container1coltext',
            options={'managed': False, 'verbose_name': 'Single Column'},
        ),
        migrations.AlterModelOptions(
            name='containerwithgrid',
            options={'managed': False, 'verbose_name': 'Grid Section'},
        ),
    ]
