# Generated by Django 6.0.3 on 2026-04-06 09:14

from django.db import migrations


def rename_plugin(apps, schema_editor):
    CMSPlugin = apps.get_model("cms", "CMSPlugin")
    CMSPlugin.objects.filter(
        plugin_type="LogoCarouselPlugin",
    ).update(plugin_type="CarouselPlugin")



def reverse_rename(apps, schema_editor):
    CMSPlugin = apps.get_model("cms", "CMSPlugin")
    CMSPlugin.objects.filter(
        plugin_type="CarouselPlugin",
    ).update(plugin_type="LogoCarouselPlugin")



class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0006_benefitscard_benefitspanel_carouselitem_and_more'),
        ('djangocms_frontend', '0003_slotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
            ],
            options={
                'verbose_name': 'Carousel',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='ClientCard',
            fields=[
            ],
            options={
                'verbose_name': 'Client Card',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='CodeBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Code Block',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='CounterContainer',
            fields=[
            ],
            options={
                'verbose_name': 'Counter Panel',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='FeatureAccordionItem',
            fields=[
            ],
            options={
                'verbose_name': 'Feature Item',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
            ],
            options={
                'verbose_name': 'Heading',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='ResponsiveTable',
            fields=[
            ],
            options={
                'verbose_name': 'Responsive Table',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='Spacing',
            fields=[
            ],
            options={
                'verbose_name': 'Spacing',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.DeleteModel(
            name='LogoCarousel',
        ),
        migrations.AlterModelOptions(
            name='container1coltext',
            options={'managed': False, 'verbose_name': 'Narrow Content'},
        ),
        migrations.AlterModelOptions(
            name='containerwithgrid',
            options={'managed': False, 'verbose_name': 'Grid Section'},
        ),
        migrations.AlterModelOptions(
            name='contentteaser',
            options={'managed': False, 'verbose_name': 'Two columns'},
        ),
        migrations.AlterModelOptions(
            name='teasercontent',
            options={'managed': False, 'verbose_name': 'Content'},
        ),
        migrations.AlterModelOptions(
            name='teasermedia',
            options={'managed': False, 'verbose_name': 'Media'},
        ),
        migrations.RunPython(
            rename_plugin, reverse_code=reverse_rename
        )
    ]
