# Generated by Django 6.0.3 on 2026-04-06 12:25

from django.db import migrations



def rename_plugin(apps, schema_editor):
    CMSPlugin = apps.get_model("cms", "CMSPlugin")
    CMSPlugin.objects.filter(
        plugin_type="FeaturesPlugin",
    ).update(plugin_type="AccordionPlugin")
    CMSPlugin.objects.filter(
        plugin_type="FeatureAccordionItemPlugin",
    ).update(plugin_type="AccordionItemPlugin")



def reverse_rename(apps, schema_editor):
    CMSPlugin = apps.get_model("cms", "CMSPlugin")
    CMSPlugin.objects.filter(
        plugin_type="AccordionPlugin",
    ).update(plugin_type="FeatureAccordionItemPlugin")
    CMSPlugin.objects.filter(
        plugin_type="AccordionItemPlugin",
    ).update(plugin_type="FeatureAccordionItemPlugin")


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0007_carousel_clientcard_codeblock_countercontainer_and_more'),
        ('djangocms_frontend', '0003_slotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
            ],
            options={
                'verbose_name': 'Accordion',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
            ],
            options={
                'verbose_name': 'Accordion Item',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.DeleteModel(
            name='FeatureAccordionItem',
        ),
        migrations.DeleteModel(
            name='FeatureHanging',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.RunPython(rename_plugin, reverse_code=reverse_rename)
    ]
