# Generated by Django 6.0.3 on 2026-04-07 06:21

from django.db import migrations


def rename_plugin(apps, schema_editor):
    CMSPlugin = apps.get_model("cms", "CMSPlugin")
    CMSPlugin.objects.filter(
        plugin_type="BenefitsPanel",
    ).update(plugin_type="BenefitsCards")



def reverse_rename(apps, schema_editor):
    CMSPlugin = apps.get_model("cms", "CMSPlugin")
    CMSPlugin.objects.filter(
        plugin_type="BenefitsCards",
    ).update(plugin_type="BenefitsPanel")


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0008_accordion_accordionitem_delete_featureaccordionitem_and_more'),
        ('djangocms_frontend', '0003_slotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsCards',
            fields=[
            ],
            options={
                'verbose_name': 'Cards',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='LinkContainer',
            fields=[
            ],
            options={
                'verbose_name': 'Centered Links',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.DeleteModel(
            name='BenefitsPanel',
        ),
        migrations.AlterModelOptions(
            name='accordionitem',
            options={'managed': False, 'verbose_name': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='benefitscard',
            options={'managed': False, 'verbose_name': 'Card'},
        ),
        migrations.AlterModelOptions(
            name='container1coltext',
            options={'managed': False, 'verbose_name': 'Narrow'},
        ),
        migrations.AlterModelOptions(
            name='containerwithgrid',
            options={'managed': False, 'verbose_name': 'Regular-width'},
        ),
        migrations.AlterModelOptions(
            name='countercontainer',
            options={'managed': False, 'verbose_name': 'Counters'},
        ),
        migrations.AlterModelOptions(
            name='ctapanel',
            options={'managed': False, 'verbose_name': 'CTA'},
        ),
        migrations.AlterModelOptions(
            name='peoplecard',
            options={'managed': False, 'verbose_name': 'Person'},
        ),
        migrations.AlterModelOptions(
            name='quotepanelcontainer',
            options={'managed': False, 'verbose_name': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='quotepanelitem',
            options={'managed': False, 'verbose_name': 'Quote'},
        ),
    ]
