# Generated by Django 6.0.3 on 2026-04-09 07:49

from django.db import migrations


def rename_plugin(apps, schema_editor):
    CMSPlugin = apps.get_model("cms", "CMSPlugin")
    CMSPlugin.objects.filter(
        plugin_type="ContentTeaserPlugin",
    ).update(plugin_type="TwoColumnPlugin")



def reverse_rename(apps, schema_editor):
    CMSPlugin = apps.get_model("cms", "CMSPlugin")
    CMSPlugin.objects.filter(
        plugin_type="TwoColumnPlugin",
    ).update(plugin_type="ContentTeaserPlugin")


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0009_benefitscards_linkcontainer_delete_benefitspanel_and_more'),
        ('djangocms_frontend', '0003_slotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoColumn',
            fields=[
            ],
            options={
                'verbose_name': 'Two columns',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.DeleteModel(
            name='ContentTeaser',
        ),
        migrations.RunPython(rename_plugin, reverse_code=reverse_rename)
    ]
