# Generated by Django 6.0.3 on 2026-04-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0009_benefitscards_linkcontainer_delete_benefitspanel_and_more'),
        ('djangocms_frontend', '0003_slotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoColumn',
            fields=[
            ],
            options={
                'verbose_name': 'Two columns',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.DeleteModel(
            name='ContentTeaser',
        ),
    ]
