# Generated by Django 6.0.3 on 2026-04-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0010_twocolumn_delete_contentteaser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeaserContent',
        ),
        migrations.DeleteModel(
            name='TeaserMedia',
        ),
    ]
