# Generated by Django 6.0.3 on 2026-04-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0011_delete_teasercontent_delete_teasermedia'),
        ('djangocms_frontend', '0003_slotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaMenu',
            fields=[
            ],
            options={
                'verbose_name': 'Mega mMenu',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
