# Generated by Django 6.0.3 on 2026-04-09 14:33

from django.db import migrations



def rename_placeholders(apps, schema_editor):
    Placeholder = apps.get_model("cms", "Placeholder")

    Placeholder.objects.filter(slot="Left Column").update(slot="Blog Content")
    Placeholder.objects.filter(slot="Client Card").update(slot="Side Bar")
    Placeholder.objects.filter(slot="Post detail").update(slot="Post Footer")


def reverse_rename(apps, schema_editor):
    Placeholder = apps.get_model("cms", "Placeholder")

    Placeholder.objects.filter(slot="Blog Content").update(slot="Left Column")
    Placeholder.objects.filter(slot="Side Bar").update(slot="Client Card")
    Placeholder.objects.filter(slot="Post Footer").update(slot="Post detail")


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0011_delete_teasercontent_delete_teasermedia'),
        ('djangocms_frontend', '0003_slotmodel'),
    ]

    operations = [
        migrations.RunPython(rename_placeholders, reverse_code=reverse_rename)
    ]
