# Generated by Django 6.0.5 on 2026-05-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0013_rename_placeholders'),
        ('djangocms_frontend', '0003_slotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
            ],
            options={
                'verbose_name': 'Question',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.AlterModelOptions(
            name='megamenu',
            options={'managed': False, 'verbose_name': 'Mega Menu'},
        ),
    ]
