# Generated by Django 6.0.5 on 2026-06-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_theme', '0014_faq_faqitem_alter_megamenu_options'),
        ('djangocms_frontend', '0003_slotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneCard',
            fields=[
            ],
            options={
                'verbose_name': 'Milestone Card',
                'managed': False,
                'proxy': True,
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
